file(MAKE_DIRECTORY "${TEST_DIRECTORY}")
set(machine "${TEST_DIRECTORY}/Machine.factory")
function(run_author expected)
	execute_process(COMMAND "${FACTORYCORE_AUTHOR}" ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
	if(NOT result EQUAL expected)
		message(FATAL_ERROR "Author command failed: ${ARGN}\n${output}\n${error}")
	endif()
endfunction()
run_author(0 new "${machine}" "Integration cell")
run_author(0 add "${machine}" Cylinder "Cylinder")
run_author(0 add "${machine}" Sensor "End sensor")
run_author(0 property "${machine}" 1 Stroke 0.2)
run_author(0 place "${machine}" 2 0.2 0 0)
run_author(0 connect "${machine}" 1 Position 2 Position)
file(READ "${machine}" before)
run_author(1 property "${machine}" 1 Speed -1)
file(READ "${machine}" after)
if(NOT before STREQUAL after)
	message(FATAL_ERROR "Invalid authoring command modified the configuration")
endif()
run_author(0 disconnect "${machine}" 2 Position)
run_author(0 duplicate "${machine}" 2 "Sensor copy")
run_author(0 remove "${machine}" 1)
run_author(0 spawn "${machine}" "${EXAMPLE}" 4 0 0)
run_author(0 inspect "${machine}")
run_author(1 connect "${machine}" 4 Extended 5 Position)
run_author(1 place "${machine}" 2 nan 0 0)
run_author(1 unknown "${machine}")
